version: "3.8"

services:
  Frontend-P:
    image: webpackimage
    container_name: webpackcontainer
    stdin_open: true
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./.:/home/.
    # command: >
    #   bash -c "source /root/.nvm/nvm.sh &&
    #   nvm use --lts &&
    #   cd /home/Frontend-Parcheen &&
    #   { [ -d node_modules ] || npm install; } &&
    #   exec npm run dev -- --host"
